### ISSUE TITLE
How to configure eventeum so that it can receive the block from 0th block onwards.

### ISSUE THREAD

**Issue by saurabhsawant460** [ConsenSys/eventeum#123]
Hi
In current scenario after starting the eventeum server it receives the block from latest block onwards, so how can i configure eventeum so that it can receive block from first block onwards

**Comment by Ferparishuertas** [comment]
Hi @kevindeanjohnson11 
Thanks for your request and comments.
At @iobuilders we ha added some custom functionalities that we want to add to next Eventeum release.

One of these, allows to sync up from a given block on the network, with a given parameter
syncStartBlock

I think this option will work for you

Are you in a hurry or you can wait a while?


We envision to add new functionalities like this one, in the future, like replaying a block or a given range of blocks, but are big ideas for next internal sprints.
Kind regards

**Comment by stephen101** [comment]
Being able to sync from a specific black and get all events that match my filter since then would be very useful. +1 for this :-)

**Comment by craigwilliams84** [comment]
There are 2 ways this can now be achieved in release 0.9.0:

- Set the `initialStartBlock` configuration property.  This will take a very long time to sync up to the current block if set to zero, as it will retrieve and process every single block.
- Set the `startBlock` value on an event filter (only currently supported for event filters registered at startup via yaml configuration).  This will be more performant (but may still take some time), as it will utilise the event filtering of a node.
