### ISSUE TITLE
Node default is down!!

### ISSUE THREAD

**Issue by MaxScientist** [ConsenSys/eventeum#126]
Hi!
I am new at eventeum. I cloned eventeum and did what instructions says. When I compose it, it showed
eventeum_1   | 2020-03-26 08:21:40.380 [eventeum-scheduler1] ERROR net.consensys
.eventeum.chain.service.health.NodeHealthCheckService: checkHealth - Node defaul
t is down!!
eventeum_1   | 2020-03-26 08:21:40.378 [eventeum-scheduler1] ERROR net.consensys
.eventeum.chain.service.health.NodeHealthCheckService: isNodeConnected - Get lat
est block failed with exception on node default

I desperately deleted and cloned it over than 10 times.

**Comment by craigwilliams84** [comment]
Hi!   This is due to a failure when connecting to the configured ethereum node.  Which specific steps did you follow in the README?

**Comment by MaxScientist** [comment]
I did not configure it at all, unless i just changed the version of lombok in core. I did it because when I used command “mvn clean package”, mvn showed that some problem occured with lombok version. 
After changing and compiling project
I entered to server folder, and used following commands
Docker-compose build and up.

**Comment by craigwilliams84** [comment]
Thats strange, and implies that the parity node docker image has failed to start for some reason.  You could try running against a rinkeby infura node instead, by running `sh docker-compose.sh rinkeby` from a terminal (assuming you're using mac or linux).  If on windows, run the docker-compose commands directly, but replace with `docker-compose-rinkeby.yml`.

**Comment by craigwilliams84** [comment]
Hmmm, it seems that infura no longer supports connecting without an api key, so you would need to create a free tier account and add your api key to the ETHEREUM_NODE_URL property within `docker-compose-rinkeby.yml`.

**Comment by MaxScientist** [comment]
Thanks a lot )))))))
It did work after running on rinkeby!

**Comment by MaxScientist** [comment]
But why doesn’t it work on ordinar geth ?

**Comment by craigwilliams84** [comment]
Glad that its working!  Eventeum does support geth (and other clients), but for some reason on your machine it seems that the parity node that is run within the docker-compose script has not started correctly.  I tested on my local machine and it worked ok however.
