### ISSUE TITLE
Duplicate events when re-start eventeum

### ISSUE THREAD

**Issue by marcosio** [ConsenSys/eventeum#17]
In our test of Eventeum, we start to listen to events from our node and when we restart Eventeum, we receive again the events of the last block.

Surfing in your code, in `DefaultEventBlockManagementService.java` we locate that: The highest block from the event specification is obtained from BBDD and returned as is in the method `getLatestBlockForEvent`.

The simplest solution is to add 1 to the block number obtained from BBDD and change the method name to `getBlockNumberForScanEvent`.

**Comment by Ferparishuertas** [comment]
we added a custom fix in our eventeum version
