### ISSUE TITLE
Add support for broadcasting via an HTTP post

### ISSUE THREAD

**Issue by craigwilliams84** [ConsenSys/eventeum#3]
Currently only broadcasting via Kafka is supported but it would be useful to be able to broadcast via posting to a configured HTTP endpoint.

**Comment by gentios** [comment]
@craigwilliams84 I can see that this issue is been closed but I cannot find any related documentation on how to configure the HTTP Post broadcasting mechanism with a docker-compose file.

Can you please give me some more details regarding this.
