### ISSUE TITLE
No contract events

### ISSUE THREAD

**Issue by mestorlx** [ConsenSys/eventeum#32]
Hello this is more a support question rather than an issue.
I am testing `eventeum` with ganache-cli and I am not sure if this is supported. 
I can see the blocks events but not the contract events. The event is emitted, because with truffle I can see that the transaction response includes the properly emitted event.
In Kafka I have the following topics

```
__consumer_offsets
block-events
contract-events
filter-events
filter-events-dlteventeum
filter-events-erreventeum
filter-eventsnull
```
However the only one with messages is `block-events` which is emitted every time I perform a transaction (this is expected).
The configuration for eventeum is the default. And the version is the release 0.4 I tried with the latest from master but got same issue. 
Truffle version
Ganache CLI v6.2.5 (ganache-core: 2.3.3)
Truffle v5.0.0 (core: 5.0.0)
MacOS version 10.14.2 (18C54) Mohave
Any help will be greatly appreciated.

**Comment by craigwilliams84** [comment]
Hi, yes, ganache-cli isn't currently supported.  (It should really act the same as the real clients but for some reason it doesn't).  For testing, I advise that you use a parity chain in dev mode, which is what all the integration tests run against.  Let me know if you have any other problems.

**Comment by mestorlx** [comment]
Hi @craigwilliams84 thanks for your quick response. 
you are right its working now with ganache-cli, the problem was somewhere else.
My event was defined as:
```solidity
    enum ValueType {
        DID,               
        DIDRef,          
        DDO           
    }

    event DIDAttributeRegistered(
        bytes32 indexed did,
        address indexed owner,
        bytes32 indexed key,
        string value,
        ValueType valueType,
        uint256 updatedAt
    );
```

After I updated the event from `ValueType` to `uint256` it worked. 
The question is then that `eventeum` does not support `enums` on the event parameters?
 Would appreciate some clarification.
Thanks again for your help.

**Comment by Ferparishuertas** [comment]
Guys, last ganache version 1.2.3 works, or ganache cli 6.2.5

**Comment by mestorlx** [comment]
@craigwilliams84 Thanks for the support!
That addressed the problem closing the issue. 
Sending DM now.
