### ISSUE TITLE
Build failure: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project eventeum-core

### ISSUE THREAD

**Issue by RatanRSur** [ConsenSys/eventeum#43]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for eventeum 0.5.2-RELEASE:
[INFO]
[INFO] eventeum ........................................... SUCCESS [  2.385 s]
[INFO] eventeum-core ...................................... FAILURE [ 47.969 s]
[INFO] eventeum-server .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  52.013 s
[INFO] Finished at: 2019-05-27T10:45:09-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project eventeum-core: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :eventeum-core

**Comment by craigwilliams84** [comment]
Hey Ratan, are you still seeing this issue?  If so, what JDK are you using to compile?

**Comment by RatanRSur** [comment]
My fault! I switched to 8 and it worked

**Comment by alexrun** [comment]
@RatanRSur, where you using Java 11 previously?

**Comment by ikky888** [comment]
After doing some search on google, I came to this post. I can confirm that the same issue happened with Java 13 in my case so I will switch to Java 8 in this case.
