### ISSUE TITLE
Bug when sending Bytes32 (hex form)

### ISSUE THREAD

**Issue by vuminhquang** [ConsenSys/eventeum#47]
Hello eventeum people,
The smart contract is like that:
![image](https://user-images.githubusercontent.com/20512463/59506892-9b85ed80-8ed3-11e9-8bdd-590412982473.png)

I need to keep a bytes32 number into foo.

Right case:
If the number is created from a string like:
  let hex = web3.utils.stringToHex("Nick") // => "0x4e69636b00000000000000000000000000000000000000000000000000000000"
  send (hex)
Then from Kafka we will get this:
![image](https://user-images.githubusercontent.com/20512463/59507137-4eeee200-8ed4-11e9-988a-7042d6eb9219.png)
This string ("Nick") can be convert back to our original hex number by:
web3.utils.stringToHex(msg.details.nonIndexedParameters[0].value))

Wrong case:
If the number is just a random like:
"0x177336d08543ac4b000000000000000000000000000000000000000000000000"
On Kafka we will get an unreadable string, which CAN NOT convert back to our original number
web3.utils.stringToHex(msg.details.nonIndexedParameters[0].value))
![image](https://user-images.githubusercontent.com/20512463/59507354-fe2bb900-8ed4-11e9-88b1-ca8ba023dfaa.png)
As you see in the picture:
It's is not "177336d08543ac4b"

Think that the error is when you convert from bytes32 to string and broadcast to kafka

Sincerely,
Quang, VU

**Comment by craigwilliams84** [comment]
Hey, thanks for reporting this.  I've fixed the issue and it will be included within the next release.

**Comment by vuminhquang** [comment]
Hi, well done (y) . It's good to hear that. I'll close the issue.
