### ISSUE TITLE
Supporting for Bytes16

### ISSUE THREAD

**Issue by vuminhquang** [ConsenSys/eventeum#53]
Hello Eventeum's people,
To save the cost working with ETH, we also use Bytes16 (which is useful for hashes).
Currently, Eventeum does not support this type. May I know do you have the plan whether to support it in the near future?
You know, if we switch to Bytes32, we will get real problem doubling our cost.
Thank you.

Sincerely,
Quang, VU

**Comment by craigwilliams84** [comment]
Hey, I'll add it to the next release....gas savings are important! :)

**Comment by vuminhquang** [comment]
It's very cool to hear it. As a solution architect, I feel good to recommend your product to our project teams.
I will close the issue. Thank you :)

**Comment by craigwilliams84** [comment]
Thanks for the kind words...its appreciated.
