### ISSUE TITLE
Eventeum does not startup if one of the nodes is down

### ISSUE THREAD

**Issue by janayama** [ConsenSys/eventeum#55]
Hi there! 

We are testing the multinetwork configuration and it happens that if one of the configured nodes is down, eventeum is not starting up. This is tested agains the master version.

When starting the web3Service [here](https://github.com/ConsenSys/eventeum/blob/master/core/src/main/java/net/consensys/eventeum/chain/service/Web3jService.java#L67), it tries to connect and since it is failing eventeum stops.

We think it will be great that the service will not stop if some nodes for some reason are not reachable. 

Thank you in advance.

**Comment by Ferparishuertas** [comment]
rpc resilliency has been implemented and will be released on the next version
