### ISSUE TITLE
Using Eventeum with multiple different applications

### ISSUE THREAD

**Issue by jiaochangyang** [ConsenSys/eventeum#75]
From my understanding, Eventeum will push all contract events to the same topic (contract-events) in Kafka. Let's say that I have applications A, B, and C which are completely different apps. Now, lets I have events A, B, and C which are for the above applications, and I register all three into Eventeum. How do I ensure that application A will only process event A, application B will only process event B, and application C will only process event C? Will I have to filter on the Kafka topic?

**Comment by craigwilliams84** [comment]
Hey Chang, thats correct.  Right now Eventeum doesn't support different topics / queues for different event specifications, so a single instance for multiple apps is not natively supported.  One option is to perform some topic message filtering at the consumer as you mentioned.  Another is to implement a service between eventeum and the applications, that consumes all eventeum messages and forwards them to application specific topics, based on some configuration.  I hope that makes sense.

**Comment by jiaochangyang** [comment]
Yes! That makes sense. I guess this opens up two other questions.
1) Does this mean the intended way to use Eventeum is to have one instance running with its own isolated Kafka for each application?
2) Are there any plans to add additional user defined topics (for different applications) for Eventeum to push events into?

Thanks for the help!

**Comment by craigwilliams84** [comment]
Hey sorry about the delayed response.

1. Yes, you're correct, Thats how Eventeum is designed to be used right now.
2. I think this functionality would be cool, and its something that I've thought about.  I think if this was to be implemented, it could be in the form of an Eventeum add-on service kind of like what I described in my previous comment, sitting in the middle between the generic eventeum topics and application specific ones.  This isn't in the roadmap right now though, unfortunately. :(
