### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by KevinGuancheDarias** [ConsenSys/eventeum#84]
Hello!

How are you guys actually compiling the Project?, there are many errors, and my Eclipse won't allow me to launch it, the only way I can launch is by compiling with Maven install, and issuing `java -jar` in the target directory 

For example [AbstractBlockSubscriptionStrategy](https://github.com/ConsenSys/eventeum/blob/v0.7.0/core/src/main/java/net/consensys/eventeum/chain/service/strategy/AbstractBlockSubscriptionStrategy.java#L75) line 75, `log` property doesn't exists as of reléase **0.7.0**

Thank you in advance!

**Comment by craigwilliams84** [comment]
Hey Kevin, it seems that your Eclipse is not set up to process Lombok annotations correctly.  We use Lombok throughout Eventeum to reduce boilerplate code.  For example, in `AbstractBlockSubscriptionStrategy` the `@Slf4j` annotation automatically injects the `log` object.

I use Intellij and it works out of the box, but maybe Eclipse requires some extra configuration.

**Comment by KevinGuancheDarias** [comment]
Thank you @craigwilliams84 . I didn't get notification from the reply, don't know why, but I discovered the problem by myself, anyway, thanks for your time :smile:  :wine_glass: 

I will ebalorate the steps to get it working, so if other wants to import the project can easily.

1. Download Lombok latest version from the [official website ](https://projectlombok.org/download)
2. Double click the jar, if it doesn't launch with Java run with command line `java -jar lombok.jar`
3. Browse to your Eclipse installation, should look something like this  
![image](https://user-images.githubusercontent.com/6832422/66121642-901b1700-e5d5-11e9-854e-eea951368254.png)  
4. Click close -> restart Eclipse
5. Clean projects, and should now work properly

Extra troubleshooting: If after following the steps, Lombok doesn't work, and you are not able to launch Eventeum in Eclipse.. **check that your Eclipse .exe filename is the same than the .ini filename** , I had this problem because my STS exe was **EventeumSTS.exe** while the .ini had the original name

Best regars!
