### ISSUE TITLE
Not subscribing to Contract events while connecting to Infura

### ISSUE THREAD

**Issue by sonyjoseph** [ConsenSys/eventeum#85]
I have Eventeum pointing to Infura (Kovan network) and it is receiving the ‘New block mined’ events but not the contract events. 

Here’s the contract-event configuration:
{
"id": "FactoryDeployedEvent",
"contractAddress": "0x78be72d09cca0b296eb32ac792707034865c3efd",
"eventSpecification": {
  "eventName": "Deployed",
  "nonIndexedParameterDefinitions": [
    {"position": 0, "type": "ADDRESS"},
    {"position": 1, "type": "UINT256"}] }
}

Here are the environment variables I am setting:
export SPRING_DATA_MONGODB_HOST=localhost:27017
export ZOOKEEPER_ADDRESS=localhost:2181
export KAFKA_ADDRESSES=localhost:9092
export ETHEREUM_NODES_BLOCKSTRATEGY=PUBSUB
export ETHEREUM_BLOCKSTRATEGY=PUBSUB
export ETHEREUM_NODE_URL=wss://kovan.infura.io/ws/v3/<projectid>

I also tried setting the ETHEREUM_NODE_URL without the project id
export ETHEREUM_NODE_URL=wss://kovan.infura.io/ws

It works fine when I am connecting to Ganache but not able to get the contract events when connecting to Infura. It does works fine for a colleague of mine who is using the docker version. I am running the compiled version. 

Any thoughts on what is going on  ? Thanks

**Comment by craigwilliams84** [comment]
Hey, thats strange!  Are you using the master or development branch?

**Comment by sonyjoseph** [comment]
I am using the master branch. Should I switch to a tagged release ?

**Comment by craigwilliams84** [comment]
Master should be fine, I've only tested on mainnet and rinkeby but that shouldn't matter! Won't have time tonight but I'll try and replicate tomorrow.

**Comment by sonyjoseph** [comment]
Thanks. 
In the mean-time let me know if there are specific settings you want me to try or any additional info that can help.

**Comment by janayama** [comment]
Hey there! 

I suspect has something to do with the node network name configured.

Could you add this to your `server/src/main/resources/application.yml`

```
ethereum:
  nodes:
  - name: default
    url: <<<<yourInfuraUrlHere>>>>
    pollingInterval: ${POLLING_INTERVAL:10000}
  healthcheck:
    pollInterval: 2000
```
And repeat the steps: 

1. `mvn clean package`
2. `cd server`
3. `java -jar target/eventeum-server.jar`

@craigwilliams84 I think in Ganache it worked because the network for the name `default` is here: https://github.com/ConsenSys/eventeum/blob/master/core/src/main/resources/application.yml#L19

**Comment by sonyjoseph** [comment]
Will try it out.  Should I set the blockstrategy to PUBSUB  or keep it as POLL ?

ethereum:
  nodes:
    - name: default
      url: ${ETHEREUM_NODE_URL}
      blockStrategy: PUBSUB
  healthcheck:
    pollInterval: 2000
  blockStrategy: POLL

I have already set the ETHEREUM_NODE_URL :
export ETHEREUM_NODE_URL=wss://kovan.infura.io/ws/v3/

**Comment by janayama** [comment]
PUBSUB should be fine! :)

Let us know the result of that!

**Comment by sonyjoseph** [comment]
Still doesn't seem to be working

Here's my config:ethereum:
  nodes:
    - name: default
      url: wss://kovan.infura.io/ws
      blockStrategy: PUBSUB
  healthcheck:
    pollInterval: 2000
  blockStrategy: PUBSUB

I do see the following error in the unit tests:
14:53:56.566 [main] ERROR net.consensys.eventeum.chain.service.health.NodeHealthCheckService - Node default is down!!
14:53:56.567 [main] ERROR net.consensys.eventeum.chain.service.health.NodeHealthCheckService - Get client version failed with exception on node default
net.consensys.eventeum.chain.service.BlockchainException: Error!

With this configuration, Eventeum seems to be processing subscription events which it wasn't doing earlier:
2019-10-02 14:55:36.330 [WebSocketConnectReadThread-14] INFO  net.consensys.eventeum.chain.block.LoggingBlockListener: onBlock - New block mined. Hash: 0x2ddc34cb64c435b52ac68e8a6d839703d01edf85ed1cfebecf37629ffbe88897, Number: 13885238
2019-10-02 14:55:40.207 [WebSocketConnectReadThread-14] INFO  org.web3j.protocol.websocket.WebSocketService: processSubscriptionEvent - Processing event:
...

It isn't picking up the contract-events though

**Comment by craigwilliams84** [comment]
Hey Sony.  Sorry, I've been busy with Devcon stuff (and I'm about to get on a flight).  Are you still getting the same issue?  It must be some kind of configuration issue but I haven't had any time to debug.

**Comment by sonyjoseph** [comment]
Still having the issue. We are kind of stuck at this point. Appreciate any help in resolving it when you get the chance. Thanks 
Have a fabulous time at Devcon !!

**Comment by craigwilliams84** [comment]
@sonyjoseph Could you email the configuration that you're using, along with the abi of the deployed smart contract to craig.williams@consensys.net? I'll get to the bottom of it!

**Comment by craigwilliams84** [comment]
Hey, are you still having issues with Infura?

**Comment by sonyjoseph** [comment]
It is working fine on Ropsten so we just continued using it there than get it to work on Kovan.  Haven't tried it on Kovan after that.

**Comment by craigwilliams84** [comment]
Closing this for now, but feel free to reopen if you're still seeing this issue.
