### ISSUE TITLE
INVALIDATED events on rinkeby  infura network 

### ISSUE THREAD

**Issue by kafcioo** [ConsenSys/eventeum#89]
Hey so I have set up eventeum on local parity and all works nicely, I tried to set it up on rinkeby network and it did work fine for a bit, but very soon I started to run into issues. 

All my events get invalidated after 12 blocks 
![image](https://user-images.githubusercontent.com/9467225/66646414-fb8c6680-ec1d-11e9-858a-61f2fa4708cb.png)

The blocks are not picked automatically, I have to submit transactions in order to move blocks into my consumer. Like you need to do on your local parity

I can't change the confirmation blocks as well ... 
![image](https://user-images.githubusercontent.com/9467225/66646490-34c4d680-ec1e-11e9-9585-4963608458e6.png)

what I notice in eventum logs is that It keep throwing an error at block number 231
![image (1)](https://user-images.githubusercontent.com/9467225/66646737-f1b73300-ec1e-11e9-9ca3-8e93aff90bce.jpg)

**Comment by kafcioo** [comment]
I kind of solve it, turn out that the ws for rinkbey was not working correctly, however I can't find a good guide how to enable saving of block number into mongo db using **node js**, currently, when eventium is started it starts pulling from block 0 which is not ideal at all. 

Can anyone point me to how to store block numbers of last processed event, so in case of eventium goes down I do not have to scan the whole blockchain

**Comment by craigwilliams84** [comment]
Sorry about delayed response to this.  Eventeum should store the last seen block number and start from there on a restart...are you not seeing this behaviour?

**Comment by Ferparishuertas** [comment]
0.8.0 is out. We close it due inactivity.

Feel free to reopen if issue persists. We will be more than happy to give support

**Comment by Juan-cc** [comment]
Hi, we've been using image: eventeum/eventeum:latest (linux/amd64 DIGEST: 9ed093e0d8ea) for a while on xDAI testnet (which is SOKOL testnet), and since last week we are receiving INVALIDATED on MOST of the Events we registered to. 

Any idea how to solve this issue and start receiving CONFIRMED events again?

NOTE: SOKOL is transitioning from OpenEthereum to Nethermind.
