### ISSUE TITLE
Contract events not being emitted with ganache-cli

### ISSUE THREAD

**Issue by stephen101** [ConsenSys/eventeum#99]
I'm having an issues subscribing to contract events using Eventeum and ganache-cli. 

I can see and subscribe to block events and successfully register and delete contract events but I don't get any notifications when they are raised.

my Event looks like this :
`event PaymentScheduleCreated(
        bytes32 id,
        uint paymentLeeway,
        address owner,
        address destination,
        uint subscriptionAmount
    );`

And I subscribe like this :
`curl -X POST \
http://localhost:8060/api/rest/v1/event-filter \
-H 'Cache-Control: no-cache' \
-H 'Content-Type: application/json' \
-H 'Postman-Token: 616712a3-bf11-bbf5-b4ac-b82835779d51' \
-d '{
"id": "PaymentScheduleCreated",
"contractAddress": "0x4a936E7Ce91FD8A47bbe9aeBFabE15AA13A11232",
"eventSpecification": {
  "eventName": "PaymentScheduleCreated",
  "nonIndexedParameterDefinitions": [
    {"position": 0, "type": "BYTES32"},
    {"position": 1, "type": "UINT256"},
    {"position": 2, "type": "ADDRESS"},
    {"position": 3, "type": "ADDRESS"},
    {"position": 4, "type": "UINT256"}] }
}'`

Which returns 
`{"id":"PaymentScheduleCreated"}`

And I see this in the logs:
> Already registered contract event filter with id: PaymentScheduleCreated

Am I missing something?

**Comment by stephen101** [comment]
I can get other contract events to work, so it seems it's only that specific event that isn't working

**Comment by craigwilliams84** [comment]
Thats strange...have you checked that the ContractEventFilter entry in mongodb reflects the event filter that you've added?

**Comment by stephen101** [comment]
AhI tracked it down, after looking in ContractEventFilter I noticed the UINT256  types where registered as INT256. I think that was a typo on my side when I originally tried them out. Once I fixed this everything worked.

Is INT256 ever valid? If not I would expect an error. 

Thanks for the help.

**Comment by craigwilliams84** [comment]
I'm glad you figured out your issue!  INT256 types are valid yep; they're signed integers in solidity, whereas UINT's are unsigned.
